title: Avinash Reddy
markdown: kramdown
url: "https://avinashreddy3108.github.io"
baseurl: "/me"

# For atom feed
author:
  name: Avinash Reddy
  email: avinashreddy3108@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-postfiles

collections:
  posts:
    output: true

sass:
  style: compressed
  sourcemap: development

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
