title: Avinash Reddy
tagline: A directory of random things!
description: >-
  This is where I write stuff that I'd (hopefully) need later.
timezone: Asia/Kolkata
url: "https://avinashreddy3108.github.io"
baseurl: "/me"

markdown: kramdown

author:
  name: Avinash Reddy
  picture: https://avatars.githubusercontent.com/u/27774996?s=100
  email: avinashreddy3108@gmail.com
  socials:
    - title: Fork my stuff on GitHub!
      url: https://github.com/avinashreddy3108
      icon: fa:github

    - title: Follow me on GitLab!
      url: https://gitlab.com/avinashreddy3108
      icon: fa:gitlab

    - title: Let's chat on Telegram!
      url: https://telegram.me/avinashreddy3108
      icon: fa-brands:telegram-plane

    - title: Stalk me on Reddit!
      url: https://www.reddit.com/user/avinashreddy3108
      icon: ic:baseline-reddit

    - title: Slide into my Instagram DMs ;)
      url: https://www.instagram.com/avinashreddy3108
      icon: carbon:logo-instagram

    - title: Good ol' email is fine too :)
      url: mailto:avinashreddy3108@gmail.com
      icon: cib:mail-ru


plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-postfiles

collections:
  posts:
    output: true

sass:
  style: compressed
  sourcemap: development

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
