name: Build and deploy Jekyll site

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository.
      uses: actions/checkout@v3

    - name: Install Ruby, Bundler & required Gems.
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3
        bundler-cache: true

    - name: Build Jekyll site
      run: |
        JEKYLL_ENV=production bundle exec jekyll build

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: site
        force_orphan: true
